libname projfca 'C:\...';
options sasmstore= projfca mstored;
run;

*Perform Multiple Correspondence Analysis Data Exercice1;

ODS GRAPHICS ON;
TITLE;
TITLE1 "Multiple Correspondence Analysis";
 
FOOTNOTE;
FOOTNOTE1 "Generated by the SAS System (&_SASSERVERNAME, &SYSSCPL) on %TRIM(%QSYSFUNC(DATE(), NLDATE20.)) at %TRIM(%SYSFUNC(TIME(), TIMEAMPM12.))";
 
proc corresp mca observed dimens=2 data=projfca.arquitet outc=projfca.Coorarq plot;
   table colo fresh space desg mode func youth dyna origin eleg pov futur ;
run;
 
/* End of task code */

RUN; QUIT;
TITLE; FOOTNOTE;
ODS GRAPHICS OFF;

